apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docs
images:
  - name: harbor.squid-ink.us/politeauthority/alix-docs
    newName: harbor.squid-ink.us/politeauthority/alix-docs
    newTag: 0.0.7

resources:
  - base/deployment.yaml
  - base/service.yaml
  - base/ingress.yaml
