name: Publish

on:
  push:
    branches: ["cicd"]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: politeauthority
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Docker build
        run: |
          docker build . -t alix-docs:latest

  # publish:
  #   runs-on: self-hosted
  #   container:
  #     image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
  #     credentials:
  #       username: politeauthority
  #       password: ${{ secrets.HARBOR_PASSWORD }}
  #   strategy:
  #       fail-fast: true
  #   steps:
  #       - uses: actions/checkout@v4
  #       - name: Validate Helm - Bedrock
  #         run: |
  #           task check-helm
